const mongoose = require('mongoose')
const Schema = mongoose.Schema;
// const bcrypt = require('bcrypt')
const TransferCertificateSchema = new Schema({
    session:{
        type:String,  
    }, 
    tc_status:{
        type:String,  
    },   
    date_of_tc:{
        type:String,  
    },  
    date_of_application:{
        type:String,  
    },
    admission_no:{
        type:String,  
    },
    name:{
        type:String,  
    },
    account_no:{
        type:String,  
    },
    parents:{
        type:String,  
    },
    class_name:{
        type:String,  
    },
    section:{
        type:String,  
    },
    category:{
        type:String,  
    },
    nationality:{
        type:String,  
    },
    date_of_admission:{
        type:String,  
    },
    dob:{
        type:String,  
    },
    house:{
        type:String,  
    },
    address:{
        type:String,  
    }, 
    security_deposit:{
        type:String,  
    },
    return_mode:{
        type:String,  
    },
    bank:{
        type:String,  
    },
    tc_no:{
        type:String,  
    },
    cheque_no:{
        type:String,  
    },
    reason:{
        type:String,  
    },
    working_days:{
        type:String,  
    },
    present_days:{
        type:String,  
    },
    is_promoted:{
        type:String,  
    },
    promoted_in:{
        type:String,  
    },
    result:{
        type:String,  
    },
    last_school:{
        type:String,  
    },
    
    result_remark:{
        type:String,  
    },
    concession:{
        type:String,  
    },
    concession_remark:{
        type:String,  
    },
    games_remark:{
        type:String,  
    },
    other_remark:{
        type:String,  
    },
    conduct:{
        type:String,  
    },
    left_on:{
        type:String, 
    },
    academic_id:{
        type:String, 
    },
    student:{ type:Schema.Types.ObjectId,
        ref:"Student"
     },
},{timestamps: true}
)
mongoose.model('TransferCertificate',TransferCertificateSchema);
